import mongoose from "mongoose";
const Schema = mongoose.Schema;
const propertySchema = new Schema({
  ownerUserId: { type: mongoose.Types.ObjectId, ref: "User", required: true }, // Reference to the owner in the users collection
  propertyDetails: {
    propertyID: { type: String },
    oldPropertyID: { type: String },
    address: { type: String, required: true, trim: true },
    postCode: { type: String, required: true },
    houseNumber: { type: String },
    street: { type: String, required: true },
    town: { type: String },
    city: { type: String, required: true },
    notes: { type: String },
    location: {
      type: { type: String, default: "Point" },
      coordinates: { type: [Number], index: "2dsphere" },
    },
    propertyBoughtFor: { type: String },
    boughtAmount: { type: Number, default: 0 },
    depositAmount: { type: Number, default: 0 },
    landlordManagesAnnualPayments: { type: Boolean, default: false },
    includeInProfitLoss: { type: Boolean, default: false },
    groundRentAmount: { type: Number, default: 0 },
    serviceChargeAmount: { type: Number, default: 0 },
    rentChargeAmount: { type: Number, default: 0 },
    rentAmountForAgent: { type: String },
    rentCommission: { type: Number },
    receiptCommission: { type: Number },
    agentCommission: { type: Number },
    agentCommissionPercentage: { type: Number, default: 0 },
    rentCommissionPercentage: { type: Number, default: 0 },
    receiptCommissionPercentage: { type: Number, default: 0 },
    assets: { type: Number, default: 0 },
    agentID: { type: String },
    bedroomCount: { type: Number, default: 0 },
    boughtDate: { type: Date, default: Date.now },
    shortAddress: { type: String },
    rentCycle: { type: String, default: "Monthly" },
    rentDueDate: { type: Date },
    rentPaidDate: { type: Date },
    rentAmount: { type: Number, default: 0 },
    rentPaymentMethod: { type: String },
    rentOverdueWarning: { type: Boolean, default: false },
    rentInternalWarning: { type: Boolean, default: false },
    hmoLicence: { type: Boolean, default: true },
    professionalIndemnity: { type: Boolean, default: true },
    officeCopyDeeds: { type: Boolean, default: false },
    habitable: { type: Boolean, default: false },
    annualPaymentPayee: {
      status: { type: String },
      name: { type: String },
    },
    intendedPurpose: { type: String },
    certificates: {
      gas: { type: Boolean, default: true },
      electricity: { type: Boolean, default: true },
      epc: { type: Boolean, default: true },
      insurance: { type: Boolean, default: true },
      fireRiskAssessment: { type: Boolean, default: true },
      dAndOPolicy: { type: Boolean, default: true },
      combinedPolicy: { type: Boolean, default: true },
    },
  },
  propertyManagerId: { type: String },
  masterLock: { type: Boolean, default: false },
  currentTenantId: { type: mongoose.Types.ObjectId, ref: "users" },
  currentTenantPhoneNumber: { type: String },
  currentIenantIdDocs: { type: String },
  certRentTenancyEmails: { type: Boolean, default: false },
  maintenanceResponsibilityYN: { type: Boolean, default: false },
  leaseholdFreehold: { type: String },
  leaseExpiryDate: { type: Date },
  newTenantId: { type: mongoose.Types.ObjectId, ref: "users" },
  newTenantLeaseDate: { type: Date },
  newTenantDepositeAmount: { type: String },
  location: { type: String },
  newTenantDepositeDoneDate: { type: Date },
});

export default mongoose.model("Property", propertySchema);
